name: Test

on:
  push:
    branches:
      - master
      - renovate/**

  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test_matrix:
    strategy:
      matrix:
        node-version:
          - 18.0.0
          - 19
          - 20

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm clean-install
      - run: npm run test:ci

  # separate job to set as required in branch protection,
  # as the build names above change each time Node versions change
  test:
    runs-on: ubuntu-latest
    needs: test_matrix
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3
        with:
          node-version: lts/*
          cache: npm
      - run: npm clean-install
      - run: npm audit signatures
      - name: Ensure dependencies are compatible with the version of node
        run: npx ls-engines
      - run: npm run lint
      # https://github.com/lirantal/lockfile-lint#readme
      - name: Scan lockfile for security issues
        run: npx lockfile-lint --path package-lock.json
